// Mock data for admin dashboard

export const statsData = [
  {
    title: 'Tuyến đường',
    value: 250,
    trend: { value: '+12%', direction: 'up' as const },
    color: 'green' as const,
  },
  {
    title: 'Bộ hệ số',
    value: 45,
    trend: { value: '+5%', direction: 'up' as const },
    color: 'orange' as const,
  },
  {
    title: 'Người dùng',
    value: 156,
    trend: { value: '+8%', direction: 'up' as const },
    color: 'teal' as const,
  },
  {
    title: 'Lượt tra cứu',
    value: '1,245',
    trend: { value: '+25%', direction: 'up' as const },
    color: 'blue' as const,
  },
]

export const pricesData = [
  {
    stt: 1,
    district: 'TP. Trà Vinh',
    street: 'Đ. Phạm Thái Bường',
    segmentFrom: 'Đ. Hùng Vương',
    segmentTo: 'Vòng xoay Chợ Trà Vinh',
    priceUbnd: '36,500',
    priceLow: '247,700',
    priceHigh: '254,400',
    priceAvg: '251,000',
  },
  {
    stt: 2,
    district: 'TP. Trà Vinh',
    street: 'Đ. Điện Biên Phủ',
    segmentFrom: 'Vòng xoay Chợ',
    segmentTo: 'Đ. Phạm Hồng Thái',
    priceUbnd: '36,500',
    priceLow: '153,400',
    priceHigh: '190,500',
    priceAvg: '172,000',
  },
  {
    stt: 3,
    district: 'TP. Trà Vinh',
    street: 'Đ. Điện Biên Phủ',
    segmentFrom: 'Đ. Phạm Hồng Thái',
    segmentTo: 'Đ. Trần Phú',
    priceUbnd: '30,800',
    priceLow: '94,000',
    priceHigh: '126,000',
    priceAvg: '110,000',
  },
  {
    stt: 4,
    district: 'TP. Trà Vinh',
    street: 'Đ. Nguyễn Thị Minh Khai',
    segmentFrom: 'Đ. Lý Thường Kiệt',
    segmentTo: 'Đ. Trần Phú',
    priceUbnd: '8,500',
    priceLow: '12,000',
    priceHigh: '25,000',
    priceAvg: '18,500',
  },
  {
    stt: 5,
    district: 'H. Càng Long',
    street: 'Đ. Trần Phú',
    segmentFrom: 'Ngã 3 Càng Long',
    segmentTo: 'Cầu Càng Long',
    priceUbnd: '5,500',
    priceLow: '8,000',
    priceHigh: '15,000',
    priceAvg: '12,000',
  },
  {
    stt: 6,
    district: 'H. Cầu Kè',
    street: 'Đ. Hùng Vương',
    segmentFrom: 'UBND Huyện',
    segmentTo: 'Chợ Cầu Kè',
    priceUbnd: '4,200',
    priceLow: '6,500',
    priceHigh: '11,000',
    priceAvg: '8,500',
  },
]

export const activityData = [
  {
    type: 'add',
    user: 'Admin',
    action: 'đã thêm mới giá đất đường Nguyễn Đáng',
    time: '5 phút trước',
    color: 'green' as const,
  },
  {
    type: 'edit',
    user: 'Admin',
    action: 'đã cập nhật hệ số vị trí',
    time: '15 phút trước',
    color: 'orange' as const,
  },
  {
    type: 'user',
    user: 'Nguyễn Văn A',
    action: 'đã đăng ký tài khoản mới',
    time: '1 giờ trước',
    color: 'blue' as const,
  },
  {
    type: 'system',
    user: 'Hệ thống',
    action: 'đã sao lưu dữ liệu thành công',
    time: '2 giờ trước',
    color: 'green' as const,
  },
  {
    type: 'import',
    user: 'Admin',
    action: 'đã import dữ liệu từ Excel',
    time: '3 giờ trước',
    color: 'orange' as const,
  },
]
